# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bigfoot.drivers.ark import ark_daemon_pb2 as bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bigfoot/drivers/ark/ark_daemon_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeasurementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDaemon = channel.unary_unary(
                '/measurement_daemon.MeasurementService/RegisterDaemon',
                request_serializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.DaemonInfo.SerializeToString,
                response_deserializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.DaemonConfig.FromString,
                _registered_method=True)
        self.GetAllVantagePoints = channel.unary_unary(
                '/measurement_daemon.MeasurementService/GetAllVantagePoints',
                request_serializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.DaemonInfo.SerializeToString,
                response_deserializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.VP_ACK.FromString,
                _registered_method=True)
        self.SendVantagePoints = channel.unary_unary(
                '/measurement_daemon.MeasurementService/SendVantagePoints',
                request_serializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.VP_RESP.SerializeToString,
                response_deserializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.VP_ACK.FromString,
                _registered_method=True)
        self.GetMeasurementRequestsBulk = channel.unary_unary(
                '/measurement_daemon.MeasurementService/GetMeasurementRequestsBulk',
                request_serializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.DaemonInfo.SerializeToString,
                response_deserializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.MSM_REQ_BULK.FromString,
                _registered_method=True)
        self.SendMeasurementResultsBulk = channel.unary_unary(
                '/measurement_daemon.MeasurementService/SendMeasurementResultsBulk',
                request_serializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.MSM_RES_SHORT_BULK.SerializeToString,
                response_deserializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.MSM_ACK_BULK.FromString,
                _registered_method=True)


class MeasurementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterDaemon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllVantagePoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendVantagePoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMeasurementRequestsBulk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMeasurementResultsBulk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeasurementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDaemon': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDaemon,
                    request_deserializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.DaemonInfo.FromString,
                    response_serializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.DaemonConfig.SerializeToString,
            ),
            'GetAllVantagePoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllVantagePoints,
                    request_deserializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.DaemonInfo.FromString,
                    response_serializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.VP_ACK.SerializeToString,
            ),
            'SendVantagePoints': grpc.unary_unary_rpc_method_handler(
                    servicer.SendVantagePoints,
                    request_deserializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.VP_RESP.FromString,
                    response_serializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.VP_ACK.SerializeToString,
            ),
            'GetMeasurementRequestsBulk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMeasurementRequestsBulk,
                    request_deserializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.DaemonInfo.FromString,
                    response_serializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.MSM_REQ_BULK.SerializeToString,
            ),
            'SendMeasurementResultsBulk': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMeasurementResultsBulk,
                    request_deserializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.MSM_RES_SHORT_BULK.FromString,
                    response_serializer=bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.MSM_ACK_BULK.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'measurement_daemon.MeasurementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('measurement_daemon.MeasurementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeasurementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterDaemon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/measurement_daemon.MeasurementService/RegisterDaemon',
            bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.DaemonInfo.SerializeToString,
            bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.DaemonConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllVantagePoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/measurement_daemon.MeasurementService/GetAllVantagePoints',
            bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.DaemonInfo.SerializeToString,
            bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.VP_ACK.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendVantagePoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/measurement_daemon.MeasurementService/SendVantagePoints',
            bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.VP_RESP.SerializeToString,
            bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.VP_ACK.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMeasurementRequestsBulk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/measurement_daemon.MeasurementService/GetMeasurementRequestsBulk',
            bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.DaemonInfo.SerializeToString,
            bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.MSM_REQ_BULK.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMeasurementResultsBulk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/measurement_daemon.MeasurementService/SendMeasurementResultsBulk',
            bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.MSM_RES_SHORT_BULK.SerializeToString,
            bigfoot_dot_drivers_dot_ark_dot_ark__daemon__pb2.MSM_ACK_BULK.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
